const { sidebarsConfig } = require('./apis');

const sidebars = {
    main: [
        'welcome',
        {
            type: 'category',
            label: 'Services',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'services',
                },
            ],
        },
        {
            type: 'category',
            label: 'Standard Operating Procedures',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'sops',
                },
            ],
        },
        {
            type: 'category',
            label: 'Discord',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'discord',
                },
            ],
        },
        {
            type: 'category',
            label: 'Dev Resources',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'dev-help',
                },
            ],
        },
    ],

    ...sidebarsConfig,
};

module.exports = sidebars;
